; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27042.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\salin\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cpp"
